### ISSUE TITLE
Arnav Checklist

### ISSUE THREAD

**Issue by Arnav210** [NoahH-10/Noah_2025#19]
Preferences Tasks:

- [x] Create a preference page
- [x] Make preference page work on its own page without backend integration
- [x] Access previously chosen preferences from backend through page
- [x] Change preferences in backend through page
- [x] Change color of another page through preferences
- [x] Change color of all pages (that we wish to affect) through preferences
- [x] Add more variety to preferences

CPT requirements:

- [x] Instructions for Input from User (change color buttons)
- [x] Use of a data collection type (a dictionary to store the preferences)
- [x] At least one procedure (function) that contributes to the program (each of the functions that post and fetch data to and from the backend)
- [ ] An algorithm that includes sequencing, selection, and iteration that is in the body of selected procedure (not used)
- [x] Instructions for output (changes in the visual page based on user input)
- [x] Calls to student developed procedure (preferences page)
